### PR TITLE
fix:potential fix for issue #28

### LINKED ISSUE #28: Unable to iterate over balances
When requesting a list of all balances using Balance::all(), if the result set does not result in pagination, the ResourceCollection returned has null values for the page and records and therefore cannot be iterated over as valid() always returns false.

Screenshot 2023-01-27 at 11 52 41

### PR DESCRIPTION
**Pull request by Aman-Aalam**
# Fixes #

Improvements on how pagination meta data is calculated to provide non-null values when data is not available from the API

### Checklist

- [x] I acknowledge that all my contributions will be made under the project's license
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have titled the PR appropriately
- [x] I have updated my branch with the main branch
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation about the functionality in the appropriate .md file
- [ ] I have added inline documentation to the code I modified

If you have questions, create a GitHub Issue in this repository.

### CODE REVIEW

File: lib/PaymentRails/ResourceCollection.php [hunk 1]
```diff
@@ -41,9 +41,9 @@ class ResourceCollection implements Iterator
     public function  __construct($response, $items, $pager)
     {
         // Add "meta" fields only when they exist in JSON response
-        $this->_page = isset($response["meta"]) ? $response["meta"]["page"] : null;
+        $this->_page = isset($response["meta"]) ? $response["meta"]["page"] : 1;
         $this->_items = $items;
-        $this->_records = isset($response["meta"]) ? $response["meta"]["records"] : null;
+        $this->_records = isset($response["meta"]) ? $response["meta"]["records"] : count($items);
```
Comment (Yongyiw) [inline lib/PaymentRails/ResourceCollection.php:46]: Just to clarify that if meta not presented - we fallback to display the count of items of the page instead of the total number of records.

It should be ok since `maximumCount()` which returns $this->_records is not involved with any meaningful calculation

**Review by Yongyiw — APPROVED** [review]

File: lib/PaymentRails/ResourceCollection.php (hunk 1 above)
Comment (Aman-Aalam) [reply lib/PaymentRails/ResourceCollection.php:46]: is `count$items)` (used here) different than displaying the count of items?
